### ISSUE TITLE
change wifi network for existing AC device- end with problem with binding

### ISSUE THREAD

**Issue by MotiGross** [tomikaa87/gree-remote#54]
Hi,
i have existing AC device which i want to use on another WIFI network,
the new WIFI has different IP range
i was able to reset the WIFI settings in the device using the remote control, and was able to command it to connect with the new network(using simple hyper terminal), that's works fine, i can ping it on the new network, it answer to {"t": "scan"} , so far all good. 

i tried to send commands using the know  unique password I have used so far, he's not answering ,
it not responding to binding command with the default AES password key either. 

seem that he kind of stuck with the previous binding, any one seen something like that before?
tnx 
Moti.

**Comment by MotiGross** [comment]
i can't control it over the old network either, 
it respond to "scan" but not to binding/ commands or get status.

weird.

**Comment by tomikaa87** [comment]
Can you do another WiFi reset on the unit?

**Comment by MotiGross** [comment]
What is wifi reset on the unit?
I pressed mode+wifi to reset the current wifi settings, than with the own AP I set it to new ssid

**Comment by tomikaa87** [comment]
That's what I meant. Try to reset and connect the the AP again. What do use to connect? The python script?

**Comment by MotiGross** [comment]
I'm using my plc program, also verified with aes+ base64 encryption tool, also this code worked at the 1st time I bind the 4 ac units to my plc.
I think the code works.
I also tested with Hercules (kind of  hyper terminal with my lap top)
1at questions goes in my mind is, does the ac generate new unique passwords or the previous one I had should still works?
2nd does binding process only provides unique passwords or binding some more stuff also?

**Comment by tomikaa87** [comment]
1) I'm not sure, but I'd assume that binding or resetting WiFi generates a new unique key, so it's good idea to do a binding when you connect to the AC
2) I'm not sure what binding does internally. From the caller's perspective, it only provides the unique key. Since there is no "real" connection to the unit (it's UDP, so there is no TCP session/connection), I'd think it binding doesn't do anything other than sending out the unique key.

**Comment by MotiGross** [comment]
problem solved, i had to reset WIFI from the remote control + disconnect from power (230v) wait 5 minutes, and power back. 
and it does generate new = different unique AES password on the new WIFI network (new SSID , new IP address)

**Comment by MotiGross** [comment]
i'll add one more thing, on any binding procedure new AES unique key is generated.

**Comment by tomikaa87** [comment]
> any binding procedure new AES unique key is generated

I don't think it's possible (at least with older firmware versions). I've tried to bind to my units multiple times and always got back the same key. Also as I've mentioned, you don't have a connection session to the unit since the protocol is UDP and there is no handshaking in the Gree protocol as well, so it's not possible to identify which incoming packet belongs to which session. (Maybe it could be based on the source IP, but I don't think so)

Imagine if the key is changed with every bind, with multiple clients controlling the unit, every one of them had to bind before sending a command, every time.

However it's seems logical that the key changes when you reset the WiFi module.
